In [ ]:
!pip install pytorch-nlp

     |████████████████████████████████| 92kB 7.1MB/s 


In [ ]:
import argparse
from collections import OrderedDict
from itertools import chain
import logging
import math

import h5py
import numpy as np
import pandas as pd
from sklearn.base import TransformerMixin
import sklearn.metrics as skm
from sklearn.preprocessing import LabelBinarizer
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from torchnlp.samplers import BucketBatchSampler
from torchnlp.utils import collate_tensors
from torchnlp.encoders.text import stack_and_pad_tensors
from torchnlp.encoders.text import WhitespaceEncoder, SpacyEncoder
from numpy import vstack
from pandas import read_csv
from torch.utils.data.sampler import BatchSampler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torch.utils.data import random_split
from torch import Tensor
from torch.nn import Linear
from torch.nn import ReLU
from torch.nn import Sigmoid
from torch.nn import Module
from torch.optim import SGD
from torch.nn import BCELoss
from torch.nn.init import kaiming_uniform_
from torch.nn.init import xavier_uniform_

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!ls drive/MyDrive/Project02

project02_not_full_train.csv   project02_toloka_unlabeled.csv
project02_submission_file.csv


In [ ]:
df_train = pd.read_csv ('drive/MyDrive/Project02/project02_not_full_train.csv')

df_test = pd.read_csv ('drive/MyDrive/Project02/project02_submission_file.csv')

print (df_train)

print (df_test)

                                               Text            Label
0         Вызвать такси на семь человек до Одинцово       ORDER_TAXI
1     Самый страшный ужастик по книге Стивена Кинга       PLAY_MOVIE
2                           Анекдот с черным юмором        READ_JOKE
3                 Сколько я буду ехать до заправки?         NAVIGATE
4                              Кто такой Оксимирон?             ODQA
...                                             ...              ...
1141        Подай такси к дому через двадцать минут       ORDER_TAXI
1142                           Заказать стол в пабе  BOOK_RESTAURANT
1143                           Хочу включить музыку       PLAY_MUSIC
1144  Напомни Саше зайти к репетитору забрать книгу         REMINDER
1145           Сколько ехать сейчас до Сухаревской?         NAVIGATE

[1146 rows x 2 columns]
                                                  Text  Label
0                     Дождь закончится через два часа?    NaN
1                      

In [ ]:
dict_map = {'ORDER_TAXI': 1, 'PLAY_MOVIE': 2, 'READ_JOKE':3, 'NAVIGATE': 4,
            'ODQA': 5, 'WEATHER': 6, 'COOKING': 7, 'LEGEND': 8, 'PLAY_MUSIC':9,
            'BOOK_RESTAURANT': 10, 'REMINDER':11, 'READ_NEWS': 12, 'CALCULATOR':13,
            'SHOPPING_LIST': 14, 'P2P_TRANSFER': 15, 'CHECK_ACCOUNT ':16, 'CHECK_ACCOUNT':16, 'CURRENCY':17,
            'COMMUNAL_PAYMENTS':18, 'FAIL_FEEDBACK': 19, 'PLAY_RADIO':20,
            'SBER_PRODUCTS':21, 'HARD_COMMAND':22, 'SET_ALARM':23, 'TIME':24,
            'SET_TIMER': 25, 'CHITCHAT':26, 'CALENDAR':27}

df_train['Index_Label'] = df_train.Label.map (dict_map)

labels = df_train.drop_duplicates(subset='Label')
labels['Index_Label'] = labels.Label.map (dict_map)
print (labels)

                                                  Text  ... Index_Label
0            Вызвать такси на семь человек до Одинцово  ...           1
1        Самый страшный ужастик по книге Стивена Кинга  ...           2
2                              Анекдот с черным юмором  ...           3
3                    Сколько я буду ехать до заправки?  ...           4
4                                 Кто такой Оксимирон?  ...           5
5                            Будет дождливо в субботу?  ...           6
8                                Хочу пожарить курочку  ...           7
12                                   Я закрыла сессию!  ...           8
13             Поставь самый популярный альбом Земфиры  ...           9
14    Закажи столик на десять человек на вечер пятницы  ...          10
17                        Добавь напоминание на завтра  ...          11
23                            Прочитай новости от РБК   ...          12
24                        Пять процентов от семи сотен  ...     

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':


In [ ]:
lb = LabelBinarizer()
lb.fit(labels['Index_Label'].values)
y_train = lb.transform(df_train["Index_Label"].values)
print (y_train)

[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
encoder = SpacyEncoder(df_train.Text.values)
train_data = [{'text': encoder.encode(example), 'label': torch.FloatTensor(label)} for example, label in zip(df_train.Text.values, y_train)]
test_data = [{'text': encoder.encode(example)} for example in df_test.Text.values]

test_data[1]

{'text': tensor([  1,   1,   1,   7, 683])}

In [ ]:
batch_size = 32

train_sampler = torch.utils.data.sampler.RandomSampler(train_data)
train_batch_sampler = BucketBatchSampler(
    train_sampler, batch_size=batch_size, drop_last=True, sort_key=lambda i: 
    train_data[i]['text'].shape[0])

batches = [[train_data[i] for i in batch] for batch in train_batch_sampler]
train_batches = [collate_tensors(batch, stack_tensors=stack_and_pad_tensors) 
for batch in batches]

In [ ]:
batch_size = 1

valid_sampler = torch.utils.data.sampler.SequentialSampler(test_data)
valid_batch_sampler = BatchSampler(
    valid_sampler, batch_size=batch_size, drop_last=True)

batches = [[test_data[i] for i in batch] for batch in valid_batch_sampler]
valid_batches = [collate_tensors(batch, stack_tensors=stack_and_pad_tensors) for batch in batches]
print (valid_batches)

[{'text': BatchedSequences(tensor=tensor([[159,   1,  84, 683, 437,  28]]), lengths=tensor([6]))}, {'text': BatchedSequences(tensor=tensor([[  1,   1,   1,   7, 683]]), lengths=tensor([5]))}, {'text': BatchedSequences(tensor=tensor([[210, 305,   1,  28]]), lengths=tensor([4]))}, {'text': BatchedSequences(tensor=tensor([[  45,  714,   34,   79,   34,    8,  326,  327,   95, 1182,   34,  439]]), lengths=tensor([12]))}, {'text': BatchedSequences(tensor=tensor([[467,   7,   6,  10, 887,   1]]), lengths=tensor([6]))}, {'text': BatchedSequences(tensor=tensor([[532,  87, 154,   1]]), lengths=tensor([4]))}, {'text': BatchedSequences(tensor=tensor([[  65,  693,   95, 1306,  975]]), lengths=tensor([5]))}, {'text': BatchedSequences(tensor=tensor([[  1,  10, 267,   7,   6]]), lengths=tensor([5]))}, {'text': BatchedSequences(tensor=tensor([[1]]), lengths=tensor([1]))}, {'text': BatchedSequences(tensor=tensor([[  5, 700]]), lengths=tensor([2]))}, {'text': BatchedSequences(tensor=tensor([[161,  56,  

In [ ]:
def read_word_vectors(vectors_path):
    print("Reading word vectors... ")
    with h5py.File(vectors_path, 'r') as h5_file:
        vectors = h5_file['matrix'][...]
        words = {w.decode('utf8'): i for i, w in enumerate(h5_file['words'][...])}  # convert list to dict
    embed_dim = vectors.shape[1]
    return vectors, words, embed_dim


def get_lookup_table(word_to_id, word_vectors_path):
    voc_size = len(word_to_id)
    vectors, words, embed_dim = read_word_vectors(word_vectors_path)
    # Create lookup table
    # Words not found in embeddings index will be all-zeros.
    lookup_table = np.zeros((voc_size, embed_dim), dtype=np.float32)
    num_words_without_vector = 0
    for word, i in word_to_id.items():
        if word in words:
            lookup_table[i] = vectors[words[word]]
        else:
            num_words_without_vector += 1
    print(
        "{} unique tokens, {} without vectors".format(voc_size, num_words_without_vector))
    return lookup_table

In [ ]:
def evaluate(batches, model, criterion, device, best_f1=False):
    """
    Evaluation, return accuracy and loss
    """
    total_loss = 0.
    y_true = []
    y_pred = []

    model.eval()  # Set mode to evaluation to disable dropout & freeze BN
    sigmoid = nn.Sigmoid()
    with torch.no_grad():
        for batch in batches:
            x_batch, y_batch = batch['text'].tensor.to(device), batch['label'].tensor.to(device)
            output = model(x_batch)
            total_loss += criterion(output, y_batch)
            y_pred.extend(sigmoid(output).cpu().numpy())  # don't forget to execute sigmoid function on logits
            y_true.extend(y_batch.cpu().numpy())
    y_true = np.asarray(y_true, dtype=np.uint8)
    y_pred = np.asarray(y_pred)

    # finding the best threshold with highest f1 score
    if best_f1:
        thresholds = np.linspace(0.2, 1, 80)
        f1s = [skm.f1_score(y_true, np.array(y_pred > thr, dtype=np.uint8), average='samples') for thr in thresholds]
        best_index = np.argmax(f1s)
        return {'f1': f1s[best_index], 'threshold': thresholds[best_index], 'loss': total_loss / len(batches)}
    else:
        f1 = skm.f1_score(y_true, np.array(y_pred >= 0.5, dtype=np.uint8), average='samples')
        return {'f1': f1, 'loss': total_loss / len(batches)}


In [ ]:
class EmbeddingFromFile(nn.Embedding):
    def __init__(self,
                 word_to_id,
                 word_vectors_path):
        lookup_table = get_lookup_table(word_to_id, word_vectors_path)
        super().__init__(
            len(word_to_id),
            lookup_table.shape[1],
            _weight=torch.from_numpy(lookup_table)
        )


class ModuleParallel(nn.Module):
    """
    Execute multiple modules on the same input and concatenate the results
    """
    def __init__(self, modules: list, axis=1):
        super().__init__()
        self.modules_ = nn.ModuleList(modules)
        self.axis = axis

    def forward(self, input):
        return torch.cat([m(input) for m in self.modules_], self.axis)


class GlobalMaxPooling(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, input):
        return input.max(2)[0]

In [ ]:
class SelfAttention(nn.Module):
  def __init__(self, query_dim):
    super(Attention, self).__init__()
    self.scale = 1. / math.sqrt(query_dim)

  def forward(self, query, keys, values):
    # Query = [BxQ]
    # Keys = [TxBxK]
    # Values = [TxBxV]
    # Outputs = a:[TxB], lin_comb:[BxV]

    # Here we assume q_dim == k_dim (dot product attention)

    query = query.unsqueeze(1) # [BxQ] -> [Bx1xQ]
    keys = keys.transpose(1,2) # [TxBxK] -> [BxKxT]
    energy = torch.bmm(query, keys) # [Bx1xQ]x[BxKxT] -> [Bx1xT]
    energy = F.softmax(energy.mul_(self.scale), dim=2) # scale, normalize

    linear_combination = torch.bmm(energy, values).squeeze(1) #[Bx1xT]x[BxTxV] -> [BxV]
    return energy, linear_combination


class LSTMTextClassifier(nn.Module):
    """
    CNN-based text classifier

    It can be used for both multi-class and multi-label classification problem,
     because loss is not specified
    """

    def __init__(self,
                 num_classes,
                 word_to_id,
                 use_pretrained_word_vectors=True,
                 word_vectors_path="data/glove.42B.300d.txt",
                 trainable_word_vectors=True,
                 embed_dim=100,
                 num_layers=1,
                 bidirectional=False,
                 self_attention=False,
                 dense_sizes=(1000,),
                 dense_dropout=0.6,
                 rnn_dropout=0.0,
                 **kwargs):
        """
        :param num_classes: number of outputs (classes)
        :param word_to_id: dictionary used to compose lookup table
        :param use_pretrained_word_vectors: whether to use pre-trained word vectors
        :param word_vectors_path: path to word vectors file (should be in compatible format)
        :param trainable_word_vectors: whether to train (change) vectors
        :param embed_dim: embedding dimensionality in case of `use_pretrained_word_vectors=False`
        :param filters: number of filters (output channels) for each kernel size of the 1st CNN layer
        :param kernel_sizes: kernel sizes of the 1st CNN layer
        :param pooling_dropout: dropout coefficient after pooling layer
        :param dense_sizes: sizes of fully-connected layers
        :param dense_dropout: dropout coefficient after each fully-connected layer
        :param kwargs: ignored arguments
        """
        super().__init__()
        vocabulary_size = len(word_to_id)
        if use_pretrained_word_vectors:
            self.embed = EmbeddingFromFile(word_to_id, word_vectors_path)
        else:
            self.embed = nn.Embedding(vocabulary_size, embed_dim)

        if not trainable_word_vectors:
            self.embed.weight.requires_grad = False

        self.bi = bidirectional
        self.rnn = nn.LSTM(input_size=self.embed.embedding_dim, hidden_size=300,
                           bidirectional=bidirectional, num_layers=num_layers,
                           batch_first=True, dropout=rnn_dropout)
        self.self_attention = self_attention
        attention_dim = 300 if not self.bi else 2 * 300
        if self_attention:
            self.attention = SelfAttention(attention_dim)

        self.fcs = nn.Sequential(OrderedDict(chain(*[
            [
                ('fc{}'.format(i), nn.Linear(attention_dim, dense_sizes[i])),
                ('fc{}_bn'.format(i), nn.BatchNorm1d(dense_sizes[i])),
                ('fc{}_relu'.format(i), nn.ReLU(inplace=True)),
                ('fc{}_dp'.format(i), nn.Dropout(dense_dropout))
            ] for i in range(len(dense_sizes))
        ])))
        self.fc_last = nn.Linear(dense_sizes[-1], num_classes)

    def forward(self, x):
        # Conv1d takes in (batch, channels, seq_len), but raw embedded is (batch, seq_len, channels)
        x = self.embed(x)  # .permute(0, 2, 1)
        outputs, hidden = self.rnn(x)

        if self.self_attention:
            # attention calculation
            if self.bi:
                hidden = torch.cat([hidden[0][-1], hidden[0][-2]], dim=1)
            else:
                hidden = hidden[0][-1]
            energy, x = self.attention(hidden, outputs, outputs)
        else:
            x = outputs[:, -1, :]

        x = self.fcs(x)
        x = self.fc_last(x)
        return x

In [ ]:
device = torch.device('cuda')

model = LSTMTextClassifier(
        y_train.shape[1],
        encoder.token_to_index,
        word_vectors_path= '/content/drive/My Drive/cc.ru.300.1M.h5',
        kernel_sizes=[1, 2],
        filters=[600, 600],
        dense_sizes=[1200],
        trainable_word_vectors=True
    ).to(device)

Reading word vectors... 
1758 unique tokens, 90 without vectors


In [ ]:
optimizer = optim.Adam([p for p in model.parameters() if p.requires_grad],
                        lr=0.001, weight_decay=0)
criterion = nn.BCEWithLogitsLoss(reduction='sum')   # sigmoid

In [ ]:
for epoch in range(70):
    model.train()
    
    for batch in train_batches:
        x_batch, y_batch = batch['text'].tensor.to(device), batch['label'].tensor.to(device)
        optimizer.zero_grad()

        loss = criterion(model(x_batch), y_batch)
        loss.backward()

        # clipping gradients
        torch.nn.utils.clip_grad_norm_([p for p in model.parameters() if p.requires_grad], 1)

        optimizer.step()


    train_metrics = evaluate(train_batches, model, criterion, device)

    print('Epoch {:3}, {}'
                .format(epoch + 1, ' '.join(['train_{}: {:<6.4f}'.format(k, v) for k, v in train_metrics.items()]),
                      ))

model.eval()

Epoch   1, train_f1: 0.3402 train_loss: 361.8914
Epoch   2, train_f1: 0.7479 train_loss: 43.4370
Epoch   3, train_f1: 0.8595 train_loss: 16.3594
Epoch   4, train_f1: 0.9396 train_loss: 6.8438
Epoch   5, train_f1: 0.9786 train_loss: 4.0633
Epoch   6, train_f1: 0.9905 train_loss: 1.9396
Epoch   7, train_f1: 0.9818 train_loss: 1.8593
Epoch   8, train_f1: 0.9970 train_loss: 0.4743
Epoch   9, train_f1: 0.9955 train_loss: 0.6888
Epoch  10, train_f1: 0.9991 train_loss: 0.3047
Epoch  11, train_f1: 0.9973 train_loss: 0.3675
Epoch  12, train_f1: 0.9991 train_loss: 0.1157
Epoch  13, train_f1: 0.9982 train_loss: 0.3325
Epoch  14, train_f1: 1.0000 train_loss: 0.0722
Epoch  15, train_f1: 1.0000 train_loss: 0.0678
Epoch  16, train_f1: 1.0000 train_loss: 0.0598
Epoch  17, train_f1: 1.0000 train_loss: 0.0576
Epoch  18, train_f1: 1.0000 train_loss: 0.0578
Epoch  19, train_f1: 1.0000 train_loss: 0.0591
Epoch  20, train_f1: 1.0000 train_loss: 0.0625
Epoch  21, train_f1: 1.0000 train_loss: 0.0648
Epoch  22

LSTMTextClassifier(
  (embed): EmbeddingFromFile(1758, 300)
  (rnn): LSTM(300, 300, batch_first=True)
  (fcs): Sequential(
    (fc0): Linear(in_features=300, out_features=1200, bias=True)
    (fc0_bn): BatchNorm1d(1200, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (fc0_relu): ReLU(inplace=True)
    (fc0_dp): Dropout(p=0.6, inplace=False)
  )
  (fc_last): Linear(in_features=1200, out_features=27, bias=True)
)

In [ ]:
def predict(batch, model):
    y_pred = []
    pred_list = []
    with torch.no_grad():
          for i in range (len (batch)):
            x_batch = batch[i]['text'].tensor.to(device)
            output = model(x_batch)
            sigmoid = nn.Sigmoid()
            y_pred.extend(sigmoid(output).cpu().numpy())
            pred_list.append (y_pred)
    return y_pred

In [ ]:
pred_list = predict(valid_batches, model)

In [ ]:
index_list = []
for array in pred_list:
  a = list (array)
  index = a.index (max(a))
  index_list.append (index+1)

In [ ]:
print (index_list)

[6, 22, 5, 10, 1, 11, 9, 1, 23, 1, 7, 9, 1, 9, 2, 8, 2, 11, 6, 1, 11, 6, 25, 9, 10, 12, 9, 7, 5, 6, 9, 9, 24, 14, 9, 8, 21, 24, 2, 11, 22, 7, 11, 4, 9, 22, 11, 10, 5, 2, 8, 6, 10, 11, 6, 11, 25, 4, 21, 2, 9, 18, 22, 12, 8, 8, 17, 8, 2, 6, 20, 23, 8, 9, 14, 11, 7, 11, 9, 6, 9, 20, 23, 23, 8, 6, 8, 11, 9, 11, 3, 9, 27, 5, 22, 2, 21, 8, 17, 1, 2, 1, 8, 8, 1, 6, 8, 5, 2, 8, 8, 8, 8, 9, 8, 6, 9, 23, 8, 7, 24, 24, 23, 12, 9, 6, 9, 9, 8, 6, 5, 9, 2, 11, 7, 6, 8, 15, 23, 11, 9, 8, 10, 6, 10, 11, 9, 11, 9, 8, 7, 12, 9, 26, 18, 1, 2, 9, 7, 8, 7, 8, 10, 5, 8, 23, 18, 6, 4, 10, 8, 2, 8, 11, 1, 7, 9, 20, 6, 7, 5, 12, 11, 2, 8, 8, 6, 9, 10, 9, 9, 8, 7, 6, 6, 1, 7, 9, 8, 12, 6, 8, 7, 5, 5, 8, 11, 8, 8, 9, 2, 4, 9, 12, 8, 11, 4, 11, 21, 9, 1, 7, 8, 10, 8, 8, 10, 15, 7, 5, 1, 9, 12, 23, 8, 7, 5, 21, 4, 20, 8, 5, 7, 1, 2, 6, 2, 5, 4, 9, 8, 7, 19, 5, 9, 8, 6, 11, 8, 10, 20, 5, 9, 2, 18, 6, 10, 11, 5, 6, 9, 9, 23, 2, 23, 18, 2, 5, 9, 4, 1, 27, 22, 9, 2, 18, 13, 12, 11, 23, 11, 16, 18, 9, 9, 13, 5, 9, 12, 

In [ ]:
df_answer = df_test.copy()
df_answer ['Label'] = index_list
index_to_label = {1: 'ORDER_TAXI', 2: 'PLAY_MOVIE', 3:'READ_JOKE', 4: 'NAVIGATE',
            5: 'ODQA', 6: 'WEATHER', 7: 'COOKING', 8: 'LEGEND', 9:'PLAY_MUSIC',
            10: 'BOOK_RESTAURANT', 11:'REMINDER', 12:'READ_NEWS', 13:'CALCULATOR',
            14:'SHOPPING_LIST', 15:'P2P_TRANSFER', 16:'CHECK_ACCOUNT ', 16:'CHECK_ACCOUNT', 17:'CURRENCY',
            18:'COMMUNAL_PAYMENTS', 19:'FAIL_FEEDBACK', 20:'PLAY_RADIO',
            21:'SBER_PRODUCTS', 22:'HARD_COMMAND', 23:'SET_ALARM', 24:'TIME',
            25:'SET_TIMER', 26:'CHITCHAT', 27:'CALENDAR'}

df_answer['Label'] = df_answer.Label.map (index_to_label)
print(df_answer)
df_answer.to_csv ('vladislav.alferov_project02.csv')

                                                  Text              Label
0                     Дождь закончится через два часа?            WEATHER
1                                 Синус угла пи на два       HARD_COMMAND
2                             Какая столица Австралии?               ODQA
3    Хочу поужинать в ресторане в семь часов вечера...    BOOK_RESTAURANT
4                       Уехать на такси до станции ЗИЛ         ORDER_TAXI
..                                                 ...                ...
307                        Хочу поехать домой на такси         ORDER_TAXI
308                   Переведи одна тысяча рублей маме       P2P_TRANSFER
309                           Заплати все коммунальные  COMMUNAL_PAYMENTS
310                                 Путь до Домодедово           NAVIGATE
311  Забронировать место на двоих в самом дорогом р...    BOOK_RESTAURANT

[312 rows x 2 columns]


In [ ]:
!curl --user upload:newprolabupload -T vladislav.alferov_project02.csv 'http://de.newprolab.com/upload/' -vvv

*   Trying 85.192.32.238...
* TCP_NODELAY set
* Connected to de.newprolab.com (85.192.32.238) port 80 (#0)
* Server auth using Basic with user 'upload'
> PUT /upload/vladislav.alferov_project02.csv HTTP/1.1
> Host: de.newprolab.com
> Authorization: Basic dXBsb2FkOm5ld3Byb2xhYnVwbG9hZA==
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 21467
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 204 No Content
< Server: nginx/1.10.3 (Ubuntu)
< Date: Sun, 29 Nov 2020 16:52:52 GMT
< Connection: keep-alive
< 
* Connection #0 to host de.newprolab.com left intact
